env:
  browser: true
  es6: true
  mocha: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  BadRequest: true
  AppError: true
  NotFound: true
  request: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-param-reassign: off
}
